[mgr]
cwd = { fg = "{{colors.primary.dark.hex}}", bold = true }
border_symbol = " "
hovered = { bold = true, reversed = true }
preview_hovered = { bold = true, reversed = true }

tab_active = { fg = "{{colors.on_primary.default.hex}}", bg = "{{colors.primary.default.hex}}", bold = true }
tab_inactive = { fg = "{{colors.primary_fixed.default.hex}}", bg = "{{colors.on_primary_fixed.default.hex}}" }
tab_width = 1

find_keyword = { fg = "{{colors.error.default.hex}}", bold = true, italic = true, underline = true }
find_position = { fg = "{{colors.error.default.hex}}", bold = true, italic = true }

marker_copied = { fg = "{{colors.tertiary_fixed.default.hex | auto_lightness: 40.0}}", bg = "{{colors.tertiary_fixed.default.hex | auto_lightness: 40.0}}" }
marker_cut = { fg = "{{colors.error.default.hex}}", bg = "{{colors.error.default.hex}}" }
marker_marked = { fg = "{{colors.error.default.hex}}", bg = "{{colors.error.default.hex}}" }
marker_selected = { fg = "{{colors.tertiary.default.hex}}", bg = "{{colors.tertiary.default.hex}}" }

count_copied = { fg = "{{colors.on_tertiary_fixed.default.hex}}", bg = "{{colors.tertiary_fixed.default.hex | auto_lightness: 40.0}}" }
count_cut = { fg = "{{colors.on_error.default.hex}}", bg = "{{colors.error.default.hex}}" }
count_selected = { fg = "{{colors.on_primary.default.hex}}", bg = "{{colors.tertiary.default.hex}}" }

[mode]
normal_main = { bg = "reset", fg = "{{colors.primary.dark.hex}}", bold = true }
normal_alt = { bg = "reset", fg = "{{colors.primary.dark.hex}}" }

select_main = { bg = "{{colors.secondary.default.hex}}", fg = "{{colors.on_secondary.default.hex}}", bold = true }
select_alt = { bg = "{{colors.surface_variant.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" }

# Unset mode
unset_main = { bg = "{{colors.tertiary.default.hex}}", fg = "{{colors.on_tertiary.default.hex}}", bold = true }
unset_alt = { bg = "{{colors.surface_variant.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.surface_bright.default.hex}}" }
progress_error = { fg = "{{colors.error.default.hex}}", bg = "{{colors.surface_bright.default.hex}}" }

# Permissions
permissions_t = { fg = "{{colors.secondary.default.hex | auto_lightness: 30.0}}" }
permissions_w = { fg = "{{colors.tertiary.default.hex | auto_lightness: 30.0}}" }
permissions_x = { fg = "{{colors.error.default.hex | auto_lightness: 30.0}}" }
permissions_r = { fg = "{{colors.tertiary_fixed.default.hex | auto_lightness: 30.0}}" }
permissions_s = { fg = "{{colors.primary_fixed.default.hex | auto_lightness: 30.0}}" }

[select]
border = { fg = "{{colors.primary.default.hex}}" }
active = { fg = "{{colors.tertiary.default.hex}}", bold = true }
inactive = {}

[input]
border = { fg = "{{colors.primary.default.hex}}" }
value = { fg = "{{colors.on_surface.default.hex}}" }

[completion]
border = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.on_primary.default.hex}}" }

[tasks]
border = { fg = "{{colors.primary.default.hex}}" }
title = {}
hovered = { fg = "{{colors.tertiary_fixed.default.hex}}", underline = true }

[which]
cols = 3
mask = { bg = "{{colors.surface_bright.default.hex}}" }
cand = { fg = "{{colors.primary.default.hex}}" }
rest = { fg = "{{colors.on_primary.default.hex}}" }
desc = { fg = "{{colors.on_surface.default.hex}}" }
separator = " â–¶ "
separator_style = { fg = "{{colors.on_surface.default.hex}}" }

[help]
on = { fg = "{{colors.on_surface.default.hex}}" }
run = { fg = "{{colors.on_surface.default.hex}}" }
footer = { fg = "{{colors.on_secondary.default.hex}}", bg = "{{colors.secondary.default.hex}}" }


[tabs]
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[status]
overall = {}
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }


[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#5AD4E6" },

  # Media
  { mime = "{audio,video}/*", fg = "#FCE566" },

  # Archives
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#FC618D" },

  # Documents
  { mime = "application/{pdf,doc,rtf}", fg = "#7BD88F" },

  # Special files
  { name = "*", is = "orphan", bg = "#FC618D" },
  { name = "*", is = "exec", fg = "{{colors.on_error_container.default.hex}}" },

  # Dummy files
  { name = "*", is = "dummy", bg = "#FC618D" },
  { name = "*/", is = "dummy", bg = "#FC618D" },
  { mime = "inode/{,x-}empty", fg = "#FC618D" },

  # Fallback
  { name = "*", fg = "{{colors.on_surface.default.hex}}" },
  { name = "*/", fg = "{{colors.surface_tint.default.hex}}" },
]
